### ISSUE TITLE
Debian installer

### ISSUE THREAD

**Issue by rllola** [ShibeTechnology/dogecoin-spv-node#8]
Create a .deb for install

**Comment by MalikMlitat** [comment]
Hey @rllola  
I would try to start with this task and provide a .deb package

**Comment by MalikMlitat** [comment]
@rllola we have 2 optiones:

1. I saw that there is a [linux](https://github.com/ShibeTechnology/dogecoin-spv-node/releases/download/v0.5.2/dogecoin-spv-0.5.2-linux-x64.tar.gz) release, and the binaries can be used to  create a binary package out of it, or 
2. shall the debian be built from source?

**Comment by rllola** [comment]
Hey!
Yes Option 1 is a good way to go. The release has an embedded node engine so you don't have anything else to install. I am reviewing your PR. Thank you for the contribution.
